apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pvc
spec:
  storageClassName: do-block-storage # must be the same as storage-class
  accessModes:
    - ReadWriteOnce #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 8Gi
