apiVersion: v1
kind: Secret
metadata:
  name: my-registry-secret
  namespace: my-namespace
  labels:
    tier: prod
data:
  .dockerconfigjson: base64 encoded output from ~/.docker/config.json goes here(cat ~/.docker/config.json | base64(note place the ouput on 1 line here)
type: kubernetes.io/dockerconfigjson 
