apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: wp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wp
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 350Mi
