apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wp
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
