---
apiVersion: v1
kind: Service
metadata:
  name:  wp-service
spec:
  selector:
    app: wp
  type: ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wordpress:5.6.0 # Very important
        #readinessProbe:
          #httpGet:
            #path: /health
            #port: 80
          #initialDelaySeconds: 5
        #livenessProbe:
          #httpGet:
            #path: /health
            #port: 80
          #initialDelaySeconds: 5
          #periodSeconds: 30
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_USER
          value: wp
        - name: WORDPRESS_DB_NAME
          value: custom_db_name
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wpuser
              key: password
        volumeMounts:
          - mountPath: /var/www/html
            name: wordpress-persistent-storage
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-nfs-pvc
